spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/servicedesk
    username: servicedesk
    password: ${POSTGRES_PASSWORD:servicedesk}

  data:
    redis:
      host: redis
      port: 6379
    elasticsearch:
      uris: http://elasticsearch:9200

logging:
  level:
    root: INFO
    com.servicedesk: INFO

server:
  port: 8080
